### ISSUE TITLE
Uncaught ReferenceError: Waypoint is not defined

### ISSUE THREAD

**Issue by mindsize** [woothemes/storefront-sticky-add-to-cart#2]
It looks like Divi Builder (the plugin, not the theme) uses a different version of jQuery Waypoints that is causing a conflict with the version packaged with Storefront Sticky Add To Cart.

![screenshot 2015-12-02 16 48 22](https://cloud.githubusercontent.com/assets/938513/11546809/0c13abf4-9915-11e5-9e05-ad8305d1c4c3.png)

![screenshot 2015-12-02 16 52 46](https://cloud.githubusercontent.com/assets/938513/11546827/2550e276-9915-11e5-83e8-3d07492d8c4d.png)

![screenshot 2015-12-02 16 53 43](https://cloud.githubusercontent.com/assets/938513/11546852/4588ef66-9915-11e5-97c9-ac7fbfc78fa3.png)

**Comment by jameskoster** [comment]
I'm using the latest version. They should probably update. 2.0.2 is nearly 3 years old.

**Comment by mindsize** [comment]
James, I'll reach out to ET and see if they can get this fixed. Sorry, I didn't realize this was squarely on their end, and I should have checked first :)

**Comment by jameskoster** [comment]
np dude :)

**Comment by mindsize** [comment]
James, just wanted to follow up and let you know that I did get ET to update the version of Waypoints that they're using, so the latest Divi and Extra releases, and the Divi Builder plugin, should all be compatible nows 👍
