### ISSUE TITLE
Bar is is transparent when it should be opaque

### ISSUE THREAD

**Issue by keninbassart** [woothemes/storefront-sticky-add-to-cart#3]
WooCommerce 2.5.0 WordPress 4.4.1 Storefront 1.6.1

When the sticky bar is on screen it is translucent

![translucent](http://cld.wthms.co/19IKw/1FokV2Rt+)

Strangely in the Customizer it renders as opaque

![opaque](http://cld.wthms.co/15cjl/2svg5rfI+)

It was also reported by a user here: https://wordpress.org/support/topic/it-looks-transparent

**Comment by jameskoster** [comment]
Hmm, perhaps the background color has been unset. Try changing it, saving, then reverting.

**Comment by keninbassart** [comment]
@jameskoster  - That appears to have resolved it

**Comment by jameskoster** [comment]
:+1:
